spring.application.name=webapp
server.port=8080
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.security.user.name=monei
spring.security.user.password=12